--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: keycloak
    name: keycloak
  name: keycloak
spec: 
  ports: 
    - 
      name: http
      nodePort: 30080
      port: 8080
      protocol: TCP
  selector: 
    app: keycloak
    name: keycloak
  type: NodePort